services:

  postgres:
    container_name: sql-bootcamp
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - sql_bootcamp_data:/var/lib/postgresql/data
volumes:
  sql_bootcamp_data: